name: newsqa-es
dependencies:
  -              cudatoolkit=11.3
  -              python=3.9
  -     pytorch::pytorch=1.11
  -              sentencepiece
  -              tqdm
  - conda-forge::transformers=4.15
